### ISSUE TITLE
Ошибка Notice: Undefined offset: 1

### ISSUE THREAD

**Issue by woodyfon** [amironov73/PhpIrbis#1]
При использовании примеров и включенном error_reporting(-1) появляются ошибки-уведомления типа Notice: Undefined offset: 1 в функции public function parse(array $lines) классов IniFile и FoundLine.

Необходимо добавить перед определением $parts[1]
```
if (  !isset($parts[1]) ) {
   $parts[1] = null;
}
```

или выполнить другую проверку элементов в массиве.

**Comment by amironov73** [comment]
Обернул такие обращения функцией safe_get, смотрите 731d824
