### ISSUE TITLE
WRONG_PROTOCOL $connectino->readRecord

### ISSUE THREAD

**Issue by jenia0jenia** [amironov73/PhpIrbis#11]
при чтении записи методом $connection->readRecord() выдаёт ошику 2222 WRONG_PROTOCOL /

readRecordVersion срабатывает без ошибок

Если добавить в readRecord эту строку, то проблема уходит
`$query->add(0);`

**Comment by woodyfon** [comment]
Метод readRecord требует обязательно указывать номер записи (MFN).
См. описание метода [readRecord](https://github.com/amironov73/PhpIrbis/blob/master/Source/PhpIrbis.php#L4889)
Попробуйте, в скобках указать номер записи, например, 100.
Вот так:
$connection->readRecord(100);

**Comment by amironov73** [comment]
Приведите, пожалуйста, минимальный код, воспроизводящий проблему. PhpIrbis больше 5 лет используется в нескольких библиотеках, и до сих пор на функцию `readRecord` нареканий не было. Хочется узнать, в каком сценарии она работает неверно.

**Comment by jenia0jenia** [comment]
Код для теста таков - 
```
<?php
echo "HELLO!<br>\n";

$apipath = $_SERVER["DOCUMENT_ROOT"] . '/phpIrbis/Source/';
require_once $apipath.'PhpIrbis.php';
require_once $apipath.'Search.php';

$host = '***'; // скрыл ip
$port = 6666;
$username = 'test';
$password = 'test';
$database = 'PERI';
$MFN = 1;

$connection = new Irbis\Connection();
$connection->host = $host;
$connection->port = $port;
$connection->username = $username;
$connection->password = $password;
$connection->database = $database;

if (!$connection->connect()) {
    print("CONNECTION ERROR\n");
    print(Irbis\describe_error($connection->lastError));
    die();
}

echo "So, connection is ready! <br>\n";

$record = $connection->readRecord($MFN);
if (!$record) {
    print(Irbis\describe_error($connection->lastError) . "<br>\n");
    die();
}

```

Результат можно увидеть здесь
[https://pl.spb.ru/ut8/test_irbis.php](https://pl.spb.ru/ut8/test_irbis.php)

**Comment by amironov73** [comment]
Версия сервера ИРБИС64? Это "классический" сервер или "новодел" (т. е. Turbo/на Linux или еще что)?

**Comment by jenia0jenia** [comment]
![изображение](https://github.com/amironov73/PhpIrbis/assets/5387802/23c7dfef-9f65-4d82-a56f-189f49b9e71c)

**Comment by amironov73** [comment]
Т. е. это "классический" сервер ИРБИС64 на Windows?

**Comment by jenia0jenia** [comment]
Простите не понимаю, что значит классический..

**Comment by amironov73** [comment]
Т. е. не от Батрака?

**Comment by jenia0jenia** [comment]
Да, от Батрака)

**Comment by amironov73** [comment]
ОК, именно это я хотел услышать.
