### ISSUE TITLE
Поисковый язык

### ISSUE THREAD

**Issue by woodyfon** [amironov73/PhpIrbis#2]
Очень не хватает функций для формирования search- выражения на поисковом языке ИРБИСа. Это помогло бы выделить отдельную функцию для применения фильтра.
Идея состоит в том, чтобы после того, как сформирован поисковый запрос добавить в него поиск по языку, виду документа, etc.

SetFilter ( $dictionary, $values, $exclude=false )

- $dictionary префикс инверсии (словаря) - VD=
- $values as array() - массив значений
- $excludes - false или екгу - исключить записи

**Comment by amironov73** [comment]
Жду Pull Request :)

**Comment by woodyfon** [comment]
Отправил первый Pull Request. Вложенные поисковые выражения пока не рассматривал. Даже не знаю, что придумать, чтобы протестить.

**Comment by amironov73** [comment]
Взгляните на[ моё видение построителя запросов](https://github.com/amironov73/PhpIrbis/blob/master/Source/Search.php)
