### ISSUE TITLE
Кириллица в имени пользователя ERROR

### ISSUE THREAD

**Issue by woodyfon** [amironov73/PhpIrbis#5]
При использовании кириллицы в имени пользователя невозможно подключиться к серверу: Недопустимый клиент. При использовании латинницы - все хорошо.

**Comment by woodyfon** [comment]
Сейчас пишу свой класс.
Я делал так:
Изначально установил внутреннюю кодировку в `mb_internal_encoding("UTF-8");`
Скрипт сохранен в UTF-8 без BOM.
Далее не делаю перекодировку данных, а для параметра _user делаю `mb_convert_encoding($this->_user,"Windows-1251","UTF-8");`
Для словарей и поиска все хорошо!

**Comment by amironov73** [comment]
К сожалению, не могу воспроизвести ошибку "Недопустимый клиент". Прилагаю файлы, демонстрирующие работу с кириллическими логинами/паролями. У меня они отрабатывают без ошибок.

Покажите Ваш код, вызывающий указанную ошибку.

[Examples.zip](https://github.com/amironov73/PhpIrbis/files/3720226/Examples.zip)

**Comment by woodyfon** [comment]
Разобрался!
Ошибка "Недопустимый клиент" возникла не из-за кириллицы, а то что
созданному пользователю кириллицы не был доступен указанный  АРМ

сб, 12 окт. 2019 г. в 07:52, Alexey Mironov <notifications@github.com>:
