### ISSUE TITLE
Выполнение сценария глобальной корректировки

### ISSUE THREAD

**Issue by woodyfon** [amironov73/PhpIrbis#6]
```
      $query = new ClientQuery($this, '5');
        $database = $settings->database ?: $this->database;
        $query->addAnsi($database)->newLine();
        $query->add(intval($settings->actualize))->newLine();
        if (!is_null_or_empty($settings->filename)) {
            $query->addAnsi('@' . $settings->filename)->newLine();
        } else {
            $encoded = '!0' . IRBIS_DELIMITER;
            foreach ($settings->statements as $statement) {
                $encoded .= strval($statement);
            }
            $encoded .= IRBIS_DELIMITER;
            $query->addUtf($encoded)->newLine();
        }
        $query->addAnsi($settings->searchExpression)->newLine();
        $query->add($settings->firstRecord)->newLine(); // нижняя граница MFN
        $query->add($settings->numberOfRecords)->newLine(); // верхняя граница MFN
        $query->newLine(); // seqrch_seq - последовательный поиск
```
Здесь параметры firstRecord и numberOfRecords не отвечают логике по названию (ошибка в описании). Более того, если не указан search_seq (последовательный поиск) вообще не участвуют в отборе записей (последняя строка в коде) 
По сути firstRecord - нижняя граница MFN, numberOfRecords - верхняя граница MFN.

Также замечу, что сценарий глобальной корректировки должен быть в кодировке ANSI.
Поэтому его также необходимо конвертировать в ANSI. (в 4 и 5 строках оператора может присутствовать формат).
А вот search_exp кодировать не обязательно.

Такие замечания удалось выяснить после пристального изучения протокола.

**Comment by amironov73** [comment]
Благодарю за важное уточнение! Поддержка глобальной корректировки для PHP у меня была реализована некорректно.

Однако, замечу, что из того, что сценарии GBL на диске хранятся в кодировке ANSI, никак не следует, что передавать их по сети следует только в этой кодировке. Сервер ИРБИС64 прекрасно поддерживает UTF-8 в данном аспекте. Например, можно запросить следующую корректировку (полный текст см. в моём коммите):

```php
$statements = array(
        new \Irbis\GblStatement('ADD', '700', 'XXX', "'^AἈριστοτέλης'"),
        new \Irbis\GblStatement('ADD', '200', 'XXX', "'^Aアリストテレス'"),
        new \Irbis\GblStatement('ADD', '300', 'XXX', "'Пробная запись'"),
    );
```
и она отлично отработает.
![gbl](https://user-images.githubusercontent.com/2941899/69002928-067c9a00-0934-11ea-9d60-7b71883a67aa.png)
Согласитесь, эти символы никак не помещаются в однобайтовую ANSI.

На будущее: первый символ восклицательного знака, передаваемый в строке с закодированными командами GBL – подсказка серверу, что дальнейший текст будет в кодировке UTF. Это недокументированная возможность протокола.

**Comment by woodyfon** [comment]
Вроде как необходимо указывать 5 параметров в сценарии ГК
1) Оператор
2) Поле/подполе
3) Повторение
4) Формат 1
5) Формат 2



вс, 17 нояб. 2019 г. в 06:23, Alexey Mironov <notifications@github.com>:

**Comment by amironov73** [comment]
Параметры глобальной корректировки запрашиваются у пользователя перед запуском этой корректировки. Пример: пакетное задание del40.gbl (удаляет в записях базы RDR посещения и возвраты до определённой даты) запрашивает дату:

![del40](https://user-images.githubusercontent.com/2941899/69014137-13e06580-09c2-11ea-87bb-988e952d26a3.png)

Пример корректировки с параметрами приводится также в документации к системе: [см. Пример 4](http://sntnarciss.ru/irbis/spravka/pril00705000000.htm)

Вот именно эти параметры пока никак не обрабатываются в PHP-версии библиотеки.

**Comment by woodyfon** [comment]
Сценарий глобальной корректировки, должен начинаться с 0 - обязательное
условие.
Если больше нуля - количество параметров, которые должен ввести
пользователь (интерактивность).
Обрабатывать параметры библиотека и не должна - этим должен заниматься
непосредственно клиент.
В любом случае на сервер должен придти пакет со строкой ГК нормального
вида.

**Comment by amironov73** [comment]
К сожалению, я не очень понял смысл выражения «строка ГК нормального вида».

Вот как производит корректировку штатный клиент `irbisbat_unicode.exe`, вызываемый из АРМ «Каталогизатор». Продемонстрирую это на примере всё той же корректировки `del40.gbl`. На диске она выглядит так:

```
1

Введите дату (ГГГГММДД). Удаление повторения, если дата возврата меньше/равна заданного значения 
DEL
991
*
XXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXX
ADD
991
XXXXXXXXXXXXXXXXXXX
'%1'
XXXXXXXXXXXXXXXXXXX
DEL
40
F
(if p(v40) then if v40^F<>'' and v40^F<>'******' and v40^F<=&uf('Av991#1') then '1' else '0' fi fi/)
XXXXXXXXXXXXXXXXXXX
DEL
991
*
XXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXX
```

При попытке выполнить её `irbisbat_unicode.exe` отправляет следующий пакет серверу  (в качестве даты я ввёл `12345678`):

```
RDR
1
!0DEL991*ADD991XXXXXXXXXXXXXXXXXXX'12345678'DEL40F(if p(v40) then if v40^F<>'' and v40^F<>'******' and v40^F<=&uf('Av991#1') then '1' else '0' fi fi/)DEL991*

0
0

1
37202
*
&
```

Ясно видно, что АРМ произвёл небольшую трансформацию сценария, в частности он заменил `%1` на введённое мною значение `12345678`.

Именно эту трансформацию я имел в виду под обработкой параметров в своей библиотеке.

**Comment by woodyfon** [comment]
Под строкой нормального вида я имел в виду, что должна начинаться с 0.
Тогда сервер ее правильно поймет и пропарсит.

**Comment by amironov73** [comment]
У меня есть подозрение, что клиент может передать на сервер ещё какие-нибудь данные, если укажет не `0` в начале сценария. Но пока мне не удалось найти то стечение обстоятельств, которое приводило бы к этому. Впрочем, возможно, подобный сценарий был заложен авторами изначально, но теперь они отказались от него.
