### ISSUE TITLE
Пример применения построителя с упрощённым формированием запроса

### ISSUE THREAD

**Issue by Zaifat** [amironov73/PhpIrbis#7]
https://github.com/amironov73/PhpIrbis/blob/master/Docs/chapter5.rst

пример не работает

**Comment by amironov73** [comment]
В чём конкретно это выражается?

**Comment by Zaifat** [comment]
```
require __DIR__ . '/vendor/autoload.php';
$client = new Irbis\Connection();
**<данные сервера>**
$client->connect();
$expression = author('Пушкин$')->and_(title('СКАЗКИ$'));
$found = client->searchCount($expression);
echo "Найдено: ", $found;
```

**Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR) in** 

поправляю на 

`$found = $client->searchCount($expression);`

**Fatal error: Uncaught Error: Call to undefined function author() in**

скрипт подключаю через композер
