### ISSUE TITLE
поиск для чайников

### ISSUE THREAD

**Issue by Zaifat** [amironov73/PhpIrbis#8]
с помощью вещей библиотеки возможно сделать аналог поиска из веб ирибса или арм читателя "поиск для чайников"
где можно просто вбить поисковых запрос который будет искать по релевантности по всем полям биб записи? Спасибо

**Comment by amironov73** [comment]
Тут вопрос, что именно подразумевается под "релевантностью". Если у вас есть четкий алгоритм вычисления релевантности записи по отношению к заданному запросу как некоторого числа, то нет никаких проблем – PhpIrbis позволяет загружать с сервера записи и проделывать над ними любые вычисления. Вычисляете релевантность записей, сортируете по убыванию и отображаете первые несколько штук.

В самой же библиотеке PhpIrbis никаких алгоритмов релевантности не заложено.

**Comment by Zaifat** [comment]
> Тут вопрос, что именно подразумевается под "релевантностью". Если у вас есть четкий алгоритм вычисления релевантности записи по отношению к заданному запросу как некоторого числа, то нет никаких проблем – PhpIrbis позволяет загружать с сервера записи и проделывать над ними любые вычисления. Вычисляете релевантность записей, сортируете по убыванию и отображаете первые несколько штук.
> 
> В самой же библиотеке PhpIrbis никаких алгоритмов релевантности не заложено.

вопрос больше к самому ирбису, чем к скрипту, функционал "поиск для чайников" на него можно сослаться при поиске через вашу библиотеку? Или это чисто внутренний функционал софта ирбис? Спасибо

**Comment by amironov73** [comment]
> вопрос больше к самому ирбису, чем к скрипту, функционал "поиск для чайников" на него можно сослаться при поиске через вашу библиотеку? Или это чисто внутренний функционал софта ирбис? Спасибо

Насколько я помню (я могу ошибаться), функциональность оценки релевантности и ранжирования записей встроена в исполняемый файл cgiirbis_64.exe, пользователям видны лишь результаты.

Некий аналог встроенного в Web-ИРБИС "поиска для чайников" я воспроизвел в скрипте `Teapot.php`, пример его использования см. папке `Examples`, скрипт `TeapotExample.php`. Надеюсь, это Вам поможет.
