### ISSUE TITLE
Notice: Trying to access array offset on value of type null in

### ISSUE THREAD

**Issue by Zaifat** [amironov73/PhpIrbis#9]
на php 7.4+ выдает предупреждение 
Notice: Trying to access array offset on value of type null in

PhpIrbis.php on line 175

заменил 
$chr = $_ansiTable[$chr];

на 
if(isset($_ansiTable[$chr])) $chr = $_ansiTable[$chr]; else $chr = 0;

**Comment by amironov73** [comment]
Исправил обращение к `$_ansiTable`
